### ISSUE TITLE
Search throws errors when traversing an object with explicit null properties

### ISSUE THREAD

**Issue by Blackbaud-ScottVossen** [formio/formio-utils#6]
I ran across this issue when using the ngFormio directive to load up some initial submission data. It is common for us to return objects that have properties that have an explicit null value in them.

For context, let's say my submission data is as follows
```
submission.data = {
  firstName: "",
  lastName: "Doe"
};
```

When the directive is loading up the form, it's using this utility to perform a getValue for each component in the form. The getValue function has an inner "search" function which traverses the submission.data object looking for the appropriate key.

```
else if (typeof data === 'object') {
        if (data.hasOwnProperty(key)) {
          return data[key];
        }
```

Since a null value will evaluate as an object in this search function, the following line will throw an exception since null doesn't have a "hasOwnProperty" function on it. 

I've added a small fix that seems to resolve this issue locally. Please look it over and let me know if there is something else you think we should be doing here.

**Comment by travist** [comment]
Fixed in https://github.com/formio/formio-utils/issues/7
